name: lost_uae
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  http: ^1.2.0
  google_sign_in: ^6.2.1
<<<<<<< HEAD
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  app_links: ^3.4.5


 



=======
  profanity_filter: ^2.0.0
>>>>>>> 43f223b5c398230b68e27b963b7c5b3a9de4ce5e

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LostUAE_LOGO.png
